import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import AIChat from "@/components/ui/AIChat"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zephyraa",
  description: "Generated by Zephyraa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-slate-900 antialiased`}>
        {/* Loader removed from here */}
        <Navbar />
        <main>
          {children}
        </main>
        <AIChat />  
        <Footer/>
      </body>
    </html>
  );
}