import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Loader from "@/components/ui/Loader"; 
import AIChat from "@/components/ui/AIChat"; // Import the new component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zephyraa",
  description: "Generated by Zephyraa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-black text-slate-900 dark:text-slate-200 transition-colors duration-300`}>
        <Loader />
        <Navbar />
        {children}
        <AIChat /> {/* Add it here */}
        <Footer/>
      </body>
    </html>
  );
}